### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by LuisAlexisMorales** [SistemasTecTlaxiaco/infografia-LuisAlexisMorales#2]
[Infografia Creaativa Proyecto Ilustrado Colorido.pdf](https://github.com/SistemasTecTlaxiaco/infografia-LuisAlexisMorales/files/12593368/Infografia.Creaativa.Proyecto.Ilustrado.Colorido.pdf)

**Comment by 00Asaf00** [comment]
El link al PDF redirige a la pagina ya abierta. Favor de solucionarlo.

**Comment by 00Asaf00** [comment]
Redacción y ortografía: 95% (Falla solo en las mayúsculas)
Exposición de Ideas Centrales: 70%
Organización de Ideas centrales: 50%
Uso de imágenes y colores: 50%
Presentación Visual: 70%
Referencias: 0%

Calificación: 0.2*56 = 12

**Comment by josealfredo79** [comment]
Revisado...
